ci:
    # pre-commit ci do not install dependencies from setup.py
  skip: [actionlint-docker, check-github-actions]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v6.0.0'
  hooks:
  - id: check-merge-conflict
    exclude: "rst$"
  - id: check-case-conflict
  - id: check-json
  - id: check-xml
  - id: check-yaml
  - id: check-added-large-files
  - id: end-of-file-fixer
    exclude: "[.]md$"
  - id: trailing-whitespace
    exclude: "[.]md$"
  - id: check-symlinks
  - id: file-contents-sorter
    files: |
      docs/spelling_wordlist.txt|
      .gitignore
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.16.6
  hooks:
  - id: ruff-check
    args: [--fix]
  - id: ruff-format
- repo: https://github.com/rhysd/actionlint
  rev: v1.7.12
  hooks:
  - id: actionlint-docker
    args:
    - -ignore
    - 'SC2155:'
    - -ignore
    - 'SC2086:'
    - -ignore
    - 'SC1004:'
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.38.0
  hooks:
  - id: check-github-actions
