name: CI

on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
    branches: [master]
  schedule:
    - cron: 0 12 * * *

jobs:
  test:
    name: All checks are passed
    uses: ./.github/workflows/test.yaml
    secrets: inherit

  approve:
    name: Approve bot PR
    runs-on: ubuntu-latest
    if: endsWith(github.actor, '[bot]')
    needs: test
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: metadata
        id: metadata
        if: github.actor == 'dependabot[bot]'
        uses: dependabot/fetch-metadata@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable auto-merge for bot PRs
        run: gh pr merge --auto --squash --delete-branch "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy on PyPI
    environment: release
    needs: test
    runs-on: ubuntu-latest
    # Run only on pushing a tag
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: 3.13
      - name: Install poetry
        run: |
          pip install poetry
      - name: Sanity check for tag and version
        id: version
        run: |
          version=$(poetry version --short)
          if [ "refs/tags/v${version}" != "$GITHUB_REF" ]
          then
            echo "Tag $GITHUB_REF mismatches with ${version}"
            exit 1
          else
            echo "Tag matches version ${version}"
          fi
          echo "version=${version}" >> "$GITHUB_OUTPUT"
      - name: Build package
        run: |
          poetry build
      - name: GitHub Release
        uses: aio-libs/create-release@v1.6.6
        with:
          changes_file: CHANGELOG.md
          name: Apolo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          version: ${{ steps.version.outputs.version }}
          start_line: "[comment]: # (release notes start)"
          head_line: "Apolo {version}\\s+\\({date}\\)\n====+\n?"
          fix_issue_regex: "\\(\\[#(\\d+)\\]\\(https://github.com/neuro-inc/[^/]+/issues/\\1\\)\\)"
          fix_issue_repl: "(#\\1)"
